<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mir">
  <xacro:macro name="mir"> 
    <xacro:include filename="$(find panda_description)/urdf/include/mir.gazebo.xacro"/>
    <xacro:include filename="$(find panda_description)/urdf/include/common_properties.urdf.xacro" />
    <xacro:include filename="$(find panda_description)/urdf/include/transmissions.xacro" />

    <xacro:property name="deg_to_rad" value="0.017453293" />

    <xacro:property name="mir_base_inertial_x" value="-0.05" />
    <xacro:property name="mir_base_inertial_y" value="0.0" />
    <xacro:property name="mir_base_inertial_z" value="0.15" />
    <xacro:property name="mir_base_inertial_x_length" value="0.50" />
    <xacro:property name="mir_base_inertial_y_length" value="0.30" />
    <xacro:property name="mir_base_inertial_z_length" value="0.20" />

    <xacro:property name="mir_base_mass" value="77.0" />
    <xacro:property name="mir_act_wheel_radius" value="0.0625" />
    <xacro:property name="mir_act_wheel_width" value="0.032" />
    <xacro:property name="mir_act_wheel_mass" value="1.0" />
    <xacro:property name="mir_act_wheel_dx" value="0.037646" />
    <xacro:property name="mir_act_wheel_dy" value="0.222604" />

    <xacro:property name="mir_caster_wheel_radius" value="0.0625" />
    <xacro:property name="mir_caster_wheel_width" value="0.032" />
    <xacro:property name="mir_caster_wheel_mass" value="1.0" />
    <xacro:property name="mir_caster_wheel_dx" value="-0.0382" />
    <xacro:property name="mir_caster_wheel_dy" value="0" />
    <xacro:property name="mir_caster_wheel_dz" value="-0.094" /> 
    <xacro:property name="mir_front_caster_wheel_base_dx" value="0.3037" />
    <xacro:property name="mir_back_caster_wheel_base_dx"  value="0.3078" />
    <xacro:property name="mir_caster_wheel_base_dy" value="0.203" />
    <xacro:property name="mir_caster_wheel_base_dz" value="${mir_caster_wheel_radius - mir_caster_wheel_dz}" />

    <xacro:property name="laser_dx" value="0.392" />
    <xacro:property name="laser_dy" value="0.2358" />

    <link name="mir_base">
      <xacro:box_inertial mass="${mir_base_mass}" x="${mir_base_inertial_x_length}" y="${mir_base_inertial_y_length}" z="${mir_base_inertial_z_length}">
        <origin xyz="${mir_base_inertial_x + mir_act_wheel_dx} ${mir_base_inertial_y} ${mir_base_inertial_z}" rpy="0 0 0" />
      </xacro:box_inertial>

      <visual>
        <origin xyz="${mir_act_wheel_dx} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find panda_description)/meshes/visual/mir_250_base.stl" />
        </geometry>
        <xacro:insert_block name="material_white" />
      </visual>

      <collision>
        <origin xyz="${mir_act_wheel_dx} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find panda_description)/meshes/collision/mir_250_base.stl" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="mir_base">
      <material>Gazebo/White</material>
    </gazebo>

    <xacro:macro name="actuated_wheel" params="locationprefix locationright">
      <joint name="${locationprefix}_wheel_joint" type="continuous">
          <origin xyz="0.0 ${-mir_act_wheel_dy * locationright} ${mir_act_wheel_radius}" rpy="0 0 0" />
          <parent link="mir_base" />
          <child link="${locationprefix}_wheel_link" />
          <axis xyz="0 1 0" />
          <limit effort="100" velocity="20.0" />
      </joint>

      <link name="${locationprefix}_wheel_link">
          <xacro:cylinder_inertial mass="${mir_act_wheel_mass}" radius="${mir_act_wheel_radius}" length="${mir_act_wheel_width}">
              <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
          </xacro:cylinder_inertial>

          <visual>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
              <cylinder radius="${mir_act_wheel_radius}" length="${mir_act_wheel_width}" />
              </geometry>
              <xacro:insert_block name="material_black" />
          </visual>

          <collision>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
              <cylinder radius="${mir_act_wheel_radius}" length="${mir_act_wheel_width}" />
              </geometry>
          </collision>
      </link>

      <gazebo reference="${locationprefix}_wheel_link">
          <material>Gazebo/FlatBlack</material>
      </gazebo>
    </xacro:macro>

    <xacro:macro name="caster_wheel" params="locationprefix locationright wheel_base_dx">
      <!-- Caster Hub -->
      <joint name="${locationprefix}_caster_rotation_joint" type="continuous">
          <origin xyz="${wheel_base_dx} ${-mir_caster_wheel_base_dy * locationright} ${mir_caster_wheel_base_dz}" rpy="0 0 0" />
          <parent link="mir_base" />
          <child link="${locationprefix}_caster_rotation_link" />
          <axis xyz="0 0 1" />
          <dynamics damping="0.01" friction="0.0"/>
      </joint>

      <link name="${locationprefix}_caster_rotation_link">
          <inertial>
              <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
              <mass value="0.3097539019" />
              <inertia ixx="0.0005844517978" ixy="0" ixz="0" iyy="0.00052872551237" iyz="0" izz="0.00017923555074" />
          </inertial>

          <visual>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
              <mesh filename="file://$(find panda_description)/meshes/visual/caster_wheel_base.stl" />
              </geometry>
              <xacro:insert_block name="material_silver" />
          </visual>

          <collision>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
              <mesh filename="file://$(find panda_description)/meshes/collision/caster_wheel_base.stl" />
              </geometry>
          </collision>
      </link>

      <gazebo reference="${locationprefix}_caster_rotation_link">
          <material>Gazebo/Grey</material>
      </gazebo>

      <!-- Caster Wheel -->
      <joint name="${locationprefix}_caster_wheel_joint" type="continuous">
          <origin xyz="${mir_caster_wheel_dx} ${-mir_caster_wheel_dy * locationright} ${mir_caster_wheel_dz}" rpy="0 0 0" />
          <parent link="${locationprefix}_caster_rotation_link" />
          <child link="${locationprefix}_caster_wheel_link" />
          <axis xyz="0 1 0" />
      </joint>

      <link name="${locationprefix}_caster_wheel_link">
          <xacro:cylinder_inertial mass="${mir_caster_wheel_mass}" radius="${mir_caster_wheel_radius}" length="${mir_caster_wheel_width}">
              <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
          </xacro:cylinder_inertial>

          <visual>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
              <cylinder radius="${mir_caster_wheel_radius}" length="${mir_caster_wheel_width}" />
              </geometry>
              <xacro:insert_block name="material_black" />
          </visual>

          <collision>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
              <cylinder radius="${mir_caster_wheel_radius}" length="${mir_caster_wheel_width}" />
              </geometry>
          </collision>
      </link>

      <gazebo reference="${locationprefix}_caster_wheel_link">
          <material>Gazebo/FlatBlack</material>
      </gazebo>
    </xacro:macro>

    <!-- wheels -->
    <xacro:actuated_wheel locationprefix="left" locationright="-1"/>
    <xacro:actuated_wheel locationprefix="right" locationright="1"/>
    <xacro:caster_wheel locationprefix="fl" locationright="-1" wheel_base_dx="${mir_front_caster_wheel_base_dx + mir_act_wheel_dx}"/>
    <xacro:caster_wheel locationprefix="fr" locationright="1" wheel_base_dx="${mir_front_caster_wheel_base_dx + mir_act_wheel_dx}"/>
    <xacro:caster_wheel locationprefix="bl" locationright="-1" wheel_base_dx="${-mir_back_caster_wheel_base_dx + mir_act_wheel_dx}"/>
    <xacro:caster_wheel locationprefix="br" locationright="1" wheel_base_dx="${-mir_back_caster_wheel_base_dx + mir_act_wheel_dx}"/>
  </xacro:macro> 
</robot>
